### ISSUE TITLE
does this still work on phpmyadmin 5?

### ISSUE THREAD

**Issue by abubelinha** [centic9/phpmyadmin-cli#1]
Hi @centic9  
I tried to use this software but I got an error on __init__.py line 228:
```Python
    print line
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(line)?
```
I am using Python 3.8 on Windows 7.

But I get same result on Python 3.4 WinXP:

C:\>c:\python34\scripts\phpmyadmin-cli -u MYUSER --password=MYPASSWORD -l https://MYSERVER/phpmyadmin/ MYDATABASE
```
Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\python34\scripts\phpmyadmin-cli.exe\__main__.py", line 5, in <module>
  File "c:\python34\lib\site-packages\phpmyadmincli\__init__.py", line 228
    print line
             ^
SyntaxError: Missing parentheses in call to 'print'
```

I also tried [the original project](https://github.com/fdev/phpmyadmin-cli) you forked this from.
That one did not raise this error, but after login I get the same error in all my queries:
```
phpmyadmin> SHOW TABLES;
ERROR Could not execute query.
phpmyadmin> select * from test;
ERROR Could not execute query.
```
Unfortunately @fdev archived that project :cry:, so I couldn't open any issues.
Hopefully any of you still find this project useful and can take a look at this to give me advice.
For me it would be very interesting because it could let me do much more frequent updates of a web site which I can only access through phpmyadmin web interface.

Thanks a lot in advance for your help

**Comment by centic9** [comment]
For my single use case of exporting the whole DB, the repo from @fdev works fine with "Python 3.8.10" on Ubuntu. 

It seems my fork was done with Python 2.x, I now rebased onto latest from origin to make them equal.

I just forked the main repo https://github.com/fdev/phpmyadmin-cli here to contribute the "--export" option, so unfortunately I do not plan to continue active development here, but just the bare minimum to keep the tool working for me.

If you can come up with suggested improvements/fixes, I am happy to review/accept PRs.

For the error you likely need to add some more print() statements to show why the query cannot be executed, maybe something unrelated in your setup fails.

**Comment by abubelinha** [comment]
Thanks for your answer @centic9 ... which phpmyadmin version do you use?
Unfortunately my python/github skills are ~~not very high~~ pretty low.
I just opened a [phpmyadmin issue](https://github.com/phpmyadmin/phpmyadmin/issues/17423) so perhaps somebody there which knows about the interface changes in phpmyadmin 5 can help to solve this.

**Comment by abubelinha** [comment]
As you say it's working for you, I think I am not understanding the CLI options.
Would you mind to share an example call to execute a query in a remote phpmyadmin installation?
I tried this ...
>`phpmyadmin-cli -s --location=https://myserver/phpmyadmin --user=myuser --password=mypassword -e 'SELECT * FROM test_table' mydatabase`

... and I got this output:
```
Usage: phpmyadmin-cli [OPTIONS] database

phpmyadmin-cli: error: no such option: -a
```
I am on Windows 10, Python 3.9
Thanks for your help

**Comment by centic9** [comment]
I currently do the following for periodic backups successfully

`python3 phpmyadmin-cli/src/phpmyadmincli/__init__.py    --user=<dbuser>   --password=<dbpass>     --location=http://<url>/phpmyadmin/  --export-all <databbase>`

So I mostly use the "export-all" option. I don't use the others, so cannot say much about how to use them, sorry.

**Comment by centic9** [comment]
Not much more that I can do here, this repo is only a fork of the main repo. 

There is now another fork of the original repo which seems to add support for phpmyadmin 5 at https://github.com/barkanyidominik/phpmyadmin-cli-5/commit/38d48e0378d2f01a6643962e07961c5cc5a08474

**Comment by abubelinha** [comment]
Thanks for sharing. I'll try that
